SET @no=0;
SELECT @no:=@no+1 AS 'No',USR_NAMESS AS Nama, CASE WHEN USR_LEVELS = 2 THEN 'Kandidat' ELSE 'Client' END LEVEL, CASE WHEN USR_ACTIVE = 1 THEN 'Aktif' ELSE 'Tidak Aktif' END Statusnya
FROM T_MAS_USERSS 
WHERE USR_ACTIVE = 1 AND USR_LEVELS = 2 
ORDER BY USR_NAMESS;